### ISSUE TITLE
delegateMonitor wrongly shows delegate recently missing blocks

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-explorer#1]
likely due to the fact the explorer is configured for 10s blocktime in the "recently missing block". For instance showing the forging update every 10s instead of 8s.

**Comment by Doweig** [comment]
fixed in https://github.com/ArkEcosystem/ark-explorer/commit/9c678bd6fa1c158b3d2a0b8f79cb209f1bd21c4f
