### ISSUE TITLE
Explorer won't show the initial genesis address

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-explorer#10]
The explorer won't load when looking up the address used to register the genesis nodes and TEC accounts:

https://explorer.ark.io/address/AewxfHQobSc49a4radHp74JZCGP8LRe4xA

**Comment by mrv777** [comment]
Also seems fixed in latest version.  Again, this one is based closely on it for you to see:
https://explorer.ark.4miners.net/address/AewxfHQobSc49a4radHp74JZCGP8LRe4xA
