### ISSUE TITLE
Delayed transaction display

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-explorer#102]
When first connecting to an explorer, the UI comes up but the transactions do not. They take some time to load but there is no indication what is happening so people tend to reload the page as if something is wrong.

Show an indication of what is happening while we wait.

**Comment by Nasicus** [comment]
Are you talking about the transactions "data" itself or the whole page?
Because for the transactions there is now a "Loading..." which I plan later to change to a real loading indicator.

**Comment by vRobM** [comment]
Data

++ Rob

About me <https://remote.com/r>

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/ark-explorer/commit/86bd9603077987f1bf8f2a052756001c7eb5837f
