### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/ark-explorer#107]
Few hours ago an issue came up in the chart library we use https://github.com/apertureless/vue-chartjs/issues/310 so the build process is currently broken.

**Comment by faustbrian** [comment]
Solved this for now by requiring a specific version before this PR https://github.com/apertureless/vue-chartjs/pull/305 was made which broke the library https://github.com/ArkEcosystem/ark-explorer/commit/237e9e3049b8bb7d9f86b8c44f5721fb441489a0.

**Comment by apertureless** [comment]
It's now fixed with `vue-chartjs@3.2.1`

**Comment by faustbrian** [comment]
Thanks @apertureless!
