### ISSUE TITLE
Network info color

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-explorer#117]
Don't you think it looks better and is more visible if the network info is in blue?

<img width="1234" alt="screen shot 2018-02-16 at 17 43 50" src="https://user-images.githubusercontent.com/3462869/36315713-06378946-1341-11e8-909e-c43c4d4a5f23.png">

or at least something more visible

<img width="1218" alt="screen shot 2018-02-16 at 17 45 48" src="https://user-images.githubusercontent.com/3462869/36315834-547b2c16-1341-11e8-8c0a-a298caf4e7dd.png">

**Comment by faustbrian** [comment]
The color is the way it is on purpose as we didn't feel like this would need to be highlighted.
