### ISSUE TITLE
Delegate Monitor

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-explorer#118]
Order by "Last Forged" is not ordering correctly.

<img width="135" alt="screen shot 2018-02-16 at 17 52 10" src="https://user-images.githubusercontent.com/3462869/36316349-bd9f2322-1342-11e8-8d4a-b33a0a75fecc.png">

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/ark-explorer/commit/48c78d5acaac48d1de0237862c559bd1db2fa325
