### ISSUE TITLE
A few bugs on mobile browsers

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-explorer#119]
On iOS 10, using Safari, the coin symbol returns `null` instead of `Ѧ`:
![iOS 10](https://i.gyazo.com/353cf875326586b885d450fbb37b4066.jpg)

On iOS 9, the explorer doesn't even load on Safari:
![iOS 9](https://i.gyazo.com/bae04ff9763b7e4be5a091f3b4404591.jpg)

Works fine on Mobile Chrome.

However on the latest version of Chrome, searching doesn't work:

https://streamable.com/s/hzhnk/bttmkh

**Comment by Nasicus** [comment]
@faustbrian 

The page does also NOT load in Firefox (even the current explorer.ark.io version).

It appears the not showing at all is a problem of your own 
`"vue-table-component": "faustbrian/vue-table-component"`
version.
I included the real version again:
`"vue-table-component": "^1.9.0",`
and it works again.

However I know that you changed stuff in your own branch, so I didn't create a PR for this.

**Comment by faustbrian** [comment]
In Desktop Firefox or Mobile Firefox? I could only reproduce the Search Button issue with the iOS Simulator via XCode and the rest worked fine.

**Comment by Nasicus** [comment]
Desktop Firefox.

**Comment by faustbrian** [comment]
Works fine, asked a few people to test. Make sure your cache is fully flushed.

Would be helpful to get results of the console both on desktop and mobile when it doesn't work, otherwise I am just pocking around in the dark.

**Comment by Nasicus** [comment]
Hmm it appears my Firefox version was old (I think I even had like version 41 oder 57) - I don't use Firefox that often.
However since it worked with the official `vue-table-component` version but not with yours I guess it would still make sense to try to fix this?

**Comment by faustbrian** [comment]
I honestly won't try to support versions as old as Firefox 41 if that was the case.

As you can see on my fork the only thing that I changed is to add a setting that allows me to pass in an order function and without any error logs from someone for which the page didn't load I don't even have a starting point since I am pretty sure that 1 addition can't break the plugin as no behaviour was modified.

**Comment by Nasicus** [comment]
Yes I understand that you don't want to support versions as old as that :D I'm just guessing that the safari on ios 9 has the same bug (don't know how wide the distribution of this one still is).

Maybe you build your version differently than they do?

**Comment by faustbrian** [comment]
Don't think so, both using webpack, babel and vue-loader. Will take a look next week if I find time.

**Comment by vmunich** [comment]
FYI - Safari needs an iOS update to be updated, so devices that can't upgrade beyond iOS 9 or 10 can't update their Safari browser.

**Comment by alexbarnsley** [comment]
@faustbrian does that include cookies? :thinking:

**Comment by faustbrian** [comment]
Haven't checked that, could only find that Mobile Safari limits the `localStorage` and `sessionStorage` size to 0 in Private Mode.
