### ISSUE TITLE
Votes sometimes don't link to the delegate's address

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-explorer#12]
Click on the deleted vote 'sandman_53_2'. It points to https://explorer.ark.io/address/

https://explorer.ark.io/tx/a4ec0f929e9ee915ecba84d9aaf7532542268d046102b63f1f72605afd76ccd5
https://explorer.ark.io/tx/f5a55ff170f1cc57d4deacc52391d3bf3f4c0012b897350669d5ffb3d77e6ae0
https://explorer.ark.io/tx/6e2990f2ded3a9c38699dfde6ef3ab95b1de99fe0af470d3bdcd77efd5fe26fb
https://explorer.ark.io/tx/e8c0730cca49892327560e06cd472fd9e69a9ea27a1cf96d5d97913af1b9ef4d
https://explorer.ark.io/tx/163ed2e74f34af57fdc8e6cca4537ebbfe2dcb41d55456f4c919ef40cb96308c
https://explorer.ark.io/tx/baca76c004e6215875bfc48a2b4424aa154676a1833aee75e3d91c071d1e857b
https://explorer.ark.io/tx/fd47a10b6a2fb62cecc85e37703f9bbb3eac262ec4971c8404e9689059a50326

**Comment by mrv777** [comment]
This seems fixed too in the current development branch.  This explorer is based closely on the development branch to see:
https://explorer.ark.4miners.net/tx/a4ec0f929e9ee915ecba84d9aaf7532542268d046102b63f1f72605afd76ccd5
