### ISSUE TITLE
Enhancement: Add Voter balances when viewing Delegate Voters dropdown

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/ark-explorer#122]
It will be easier to see the spread of balances for the delegate

**Comment by faustbrian** [comment]
What is a delegate voters dropdown?
 If you mean https://explorer.ark.io/wallets/AdVSe37niA3uFUPgCgMUH2tMsHF4LpLoiX/voters/1 then the balance is already shown.

**Comment by vRobM** [comment]
Click on a delegate. It lists who voted for him/her.

**Comment by sleepdefic1t** [comment]
@vRobM
Can you provide screens or a mock-up of what you’re looking for?

**Comment by alexbarnsley** [comment]
I'm closing this as none of us are sure what's needed.
