### ISSUE TITLE
Enhancement: Add opt-in notifications

### ISSUE THREAD

**Issue by ciband** [ArkEcosystem/ark-explorer#138]
As a user I would like to be able to subscribe to email notifications for a given address (e.g. deposits, widthdrawals, etc..), similar to what etherscan.io provides.

I'm not sure if an account creation type solution is needed or if you can just use the "provide an email address and click the link" type pattern in order to prevent spam and such.

**Comment by faustbrian** [comment]
This is not something we plan for the near future.
