### ISSUE TITLE
design: header hover text colors

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/ark-explorer#161]
there currently are some inconsistencies in the text colors used for the links in the header:

1) the chart toggle and search icon are the only elements that get assigned a blue text color on hover
2) the currency symbol of the currency toggle is the only element with blue text color by default
3) the elements of the toggled menu use `--color-theme-text-secondary`, the elements of the currency switcher use `#3790ff`

my proposal:

all links should use `--color-theme-text-secondary` and `#037cff` on hover, using the `hover:text-blue` class. the currency symbol should be blue also in it's default state.

![image](https://user-images.githubusercontent.com/6547002/39812709-0185272c-538e-11e8-92f3-672607b5547e.png)

**Comment by dated** [comment]
if the designer agrees with the proposed changes kindly let me know, i'll submit a pr then.

**Comment by faustbrian** [comment]
Designer got back to me and said no.
