### ISSUE TITLE
Lisk Copyright and emails are Inaccurate

### ISSUE THREAD

**Issue by Isabello** [ArkEcosystem/ark-explorer#18]
Lisk copyright should state 2016-2017, not just 2017.

Author emails for Isabella Dell and Oliver Beddows should also reflect the correct email.

**Comment by fix** [comment]
are you kidding, don't you have some decent job to do!

**Comment by Isabello** [comment]
No I am not kidding. Some code was taken from our 2017 version of explorer, and since the explorer was forked in 2016 it should reflect that.

**Comment by mrv777** [comment]
I believe this can be closed now?  I'll update the emails in package.json too.
Let me know if something was missed
