### ISSUE TITLE
Node app.js - stops working 3-5 times a day

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/ark-explorer#2]
I'm running a block explorer and 3-5 times a day the block explorer's node app.js fails.

I've checked and when it fails the node on the same vps is syncing well.

The error i was getting looks like this...

Delegate Monitor: Emitting last blocks for: frank[12]
/home/jmc/ark-explorer/sockets/delegateMonitor.js:210
                        if (!existing.blocks || existing.blocks[0].timestamp < b.timestamp) {
                                                                  ^

TypeError: Cannot read property 'timestamp' of undefined
    at /home/jmc/ark-explorer/sockets/delegateMonitor.js:210:67
    at /home/jmc/ark-explorer/node_modules/async/dist/async.js:3025:16
    at replenish (/home/jmc/ark-explorer/node_modules/async/dist/async.js:882:17)
    at iterateeCallback (/home/jmc/ark-explorer/node_modules/async/dist/async.js:867:17)
    at /home/jmc/ark-explorer/node_modules/async/dist/async.js:840:16
    at /home/jmc/ark-explorer/sockets/delegateMonitor.js:219:25
    at /home/jmc/ark-explorer/node_modules/async/dist/async.js:3025:16
    at replenish (/home/jmc/ark-explorer/node_modules/async/dist/async.js:882:17)
    at iterateeCallback (/home/jmc/ark-explorer/node_modules/async/dist/async.js:867:17)
    at /home/jmc/ark-explorer/node_modules/async/dist/async.js:840:16
jmc@vultr:~/ark-explorer$ node app.js (edited)

i've also git pull'd to ensure i have the latest version.... when i restarted the node app.js the failed again within 2 mins.

I do also get a second error, but i need to capture it next time it occurs.

I'll update the issue log, when i have the second error.....

**Comment by Doweig** [comment]
Fixed in https://github.com/ArkEcosystem/ark-explorer/commit/4b0cd88b24c6c7246fecf70ffc7c677f1826dd68
