### ISSUE TITLE
Filter out dead voter wallets

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/ark-explorer#238]
The wallets of delegates have a Voters counter that currently is misleading as it contains a lot of dead wallets.

All voters below 1 ARK should be filtered out as they are most likely dead wallets from people that changed their vote and send their ARK to a fresh wallet.

Filtering out any wallets with `1 * Math.pow(10, 8)` balance should give a more realistic view of who active voters are.

**Comment by dated** [comment]
i'd filter out only those with a balance of 0 Ark. although very little, the others still have an influence on the approval and so on.

**Comment by faustbrian** [comment]
Filter out 0.1 ARK then, expecting your PR in 5 minutes :trollface:

**Comment by dated** [comment]
incoming :D

**Comment by dated** [comment]
i'm adding something real quick, for cases where we actually would want the true count.
