### ISSUE TITLE
Restore the RESTful API

### ISSUE THREAD

**Issue by dafty-1** [ArkEcosystem/ark-explorer#24]
The explorer used to provide a restful API with some useful endpoints. These have now changed to websockets.

A few of my applications have broken as a result, and most developers won't implement websockets since it's fat vs REST.

Please can we bring the RESTful API back alongside websockets?

@luciorubeens

**Comment by luciorubeens** [comment]
Hi @dafty-1, the api is enabled but running on different port: https://explorer.ark.io:8443/api

**Comment by dafty-1** [comment]
@luciorubens Ah, thanks!
