### ISSUE TITLE
npm run build:mainnet not working if served over NGINX

### ISSUE THREAD

**Issue by gsilvestri** [ArkEcosystem/ark-explorer#253]
I tried to publish the explorer built directly from sources over NGINX the result is follow:
![screenshot from 2018-06-01 17-59-10](https://user-images.githubusercontent.com/8915099/40851155-bf52215c-65c6-11e8-8178-35d2c1d4234f.png)

it seems that is not reading CSSs...

do you any of you have experienced the same problem??
To reproduce proceed as follow:

1. clone the explorer repository with `git clone git@github.com:ArkEcosystem/ark-explorer.git`
2. build from sources with `npm run build:mainnet`
3. publish `./dist` folder over NGINX

Running a local webpack server with the command `npm run dev:mainnet` displays the explorer without problems...

With ark-explorer using webpack 3.X the build server over NGINX was working as well (code of 2 months ago).

- do you any of you have experienced the same problem??
- what deployment procedure do you use into production??
- do you publish with webpack into production or with NGINX/Apache??

**Comment by ItsANameToo** [comment]
I'll take a look into this, will get back to you shortly

**Comment by ItsANameToo** [comment]
Should be fixed with #254 , issue with `MiniCssExtractPlugin` configuration while changing from webpack 3 to webpack 4.

**Comment by gsilvestri** [comment]
#254 solve the problem.

For me this issue can now be closed.

Thank You @ItsANameToo for fast reply.

**Comment by ItsANameToo** [comment]
Glad to hear :)
