### ISSUE TITLE
Network monitor shows all nodes repeatedly

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/ark-explorer#29]
/networkMonitor shows every node few times, in effect nodes counter is broken also. Example:
![9aee8afb-dc44-497a-8a43-be9399499d61](https://cloud.githubusercontent.com/assets/19519175/26626054/4125165e-45f6-11e7-92d1-53e85be10f4e.png)

**Comment by 4miners** [comment]
Fixed with https://github.com/ArkEcosystem/ark-explorer/pull/33
