### ISSUE TITLE
Small transactions are shown as exponent instead of more familiar value

### ISSUE THREAD

**Issue by dafty235** [ArkEcosystem/ark-explorer#3]
Small transactions render as exponents instead of the better known value (0.00000001).

![image](https://cloud.githubusercontent.com/assets/24987593/23261560/afcf5fa2-f9ce-11e6-8b27-a826d5debe43.png)

**Comment by Doweig** [comment]
Hey, sorry for the delay.
Got any tx id to give me to see the bug?
There's too many txs on your account http://127.0.0.1:6040/address/ASjePWudP5B2miZ7siE4mc2tgn9BY5cLtj

**Comment by dafty235** [comment]
@Doweig I'm not sure this is completely fixed:

![image](https://cloud.githubusercontent.com/assets/24987593/23804523/227f1800-05b2-11e7-8cbe-d547923e78a1.png)

**Comment by Doweig** [comment]
texplorer wasn't updated, ok now
