### ISSUE TITLE
explorer.ark.io is running in dev mode

### ISSUE THREAD

**Issue by jonaszuberbuehler** [ArkEcosystem/ark-explorer#39]
Not sure if this is an issue or if it's on purpose but according to the log NG is running in development mode: 
![image](https://user-images.githubusercontent.com/3812998/33678152-39574d20-dabb-11e7-88e6-66a15969da14.png)

**Comment by faustbrian** [comment]
Same config as the production so no big issue as there is no sensitive data that could be exposed.
