### ISSUE TITLE
Values are not forced to 8 decimal places

### ISSUE THREAD

**Issue by dafty-1** [ArkEcosystem/ark-explorer#5]
https://texplorer.ark.io/tx/97ee9253c3b1a57cd5642285ac4ff3a3d558c7a1a03aa38275602ebaa5c87d98

Since the change in #3, any values with trailing 0's don't show the trailing 0's. In this example, 0.00000610 is shown as 0.0000061.

**Comment by dafty235** [comment]
Example is 0.0000063, not 0.0000061.
On phone so can't update existing ticket.

**Comment by 4miners** [comment]
Yes, that is expected behavior. Do we really want to display all values (amounts, fees, ect.) with 8 decimal palces (like 20 ARK -> 20.00000000 ARK)?

**Comment by mrv777** [comment]
I think we want to keep the current behavior?

**Comment by dafty-1** [comment]
Yeah, moment of insanity. Close this please.
