### ISSUE TITLE
ark logo on explorer has weird line on right side

### ISSUE THREAD

**Issue by cannabanana** [ArkEcosystem/ark-explorer#7]
![screenshot 528](https://cloud.githubusercontent.com/assets/26158568/23829268/c03137a4-06a2-11e7-802b-044560841b55.png)

ark logo on the explorer has a weird color line on the right hand side. been there since day 1.

**Comment by mrv777** [comment]
I don't see this on my computer, do you still see it?

If so, can you let me know what OS and browser?
Thanks

**Comment by boldninja** [comment]
This was already corrected by me if I'm not mistaken can be closed.

**Comment by mrv777** [comment]
Thanks @boldninja
