### ISSUE TITLE
Table Heading (Suggestion)

### ISSUE THREAD

**Issue by jpgaran** [ArkEcosystem/ark-explorer#7]
It would be nice if the transaction table would have a fixed sticky header when scrolling so it would be easier for the user to know the column name while they scroll

**Comment by faustbrian** [comment]
Will be trying to take a look at this during the next few days.

**Comment by faustbrian** [comment]
Implemented, will be deployed soon. https://github.com/ArkEcosystem/ark-explorer/commit/8ca91e051253bbd2bc49be98f6b0bc49201d6a0d
