### ISSUE TITLE
Delegate monitor sort

### ISSUE THREAD

**Issue by Zarevok** [ArkEcosystem/ark-explorer#8]
Within the delegate monitor pleade asd the ability to sort by clicking on different column headings. 

Example clicking on productivity will sort by least productive delegate to most productive delegate.
Clicking on productivity a second time will sort from most productive delegate to least productive delegate.

Additionally apply sort functionaly for:
Forged
Forging Time
Status
Approval

**Comment by vmunich** [comment]
Can we re-open this for the v3?

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/ark-explorer/commit/48d700c1932eff70ba00d93af3506fef6bc7f0b9
