### ISSUE TITLE
Blocks info on the explorer possibly wrong?

### ISSUE THREAD

**Issue by cannabanana** [ArkEcosystem/ark-explorer#8]
![screenshot 533](https://cloud.githubusercontent.com/assets/26158568/23964374/836a6530-0971-11e7-97df-177a0840bf98.png)

 info for "Blocks" says unconfirmed.  Should this show which block the tx happened on?

**Comment by 4miners** [comment]
That feature require `blockId` property to be returned for transaction by core's `/api/transactions` endpoint.

**Comment by mrv777** [comment]
Fixed with https://github.com/ArkEcosystem/ark-explorer/commit/ac16cce44f995261e7c40d7b4c2b7d91dc783719
