### ISSUE TITLE
Homepage chart button disappears after usage

### ISSUE THREAD

**Issue by zarkill** [ArkEcosystem/ark-explorer#85]
After clicking the homepage chart button on Ark Explorer v3 the chart disappears as expected, but the homepage chart button itself is also gone. Cannot find any way of getting the chart (and the button) back. Refreshing the page doesn't help (probably a setting stored offline).

Using Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by zarkill** [comment]
![image](https://user-images.githubusercontent.com/19517820/35911173-591c9952-0bf9-11e8-86c7-d6e9a1bea420.png)

**Comment by faustbrian** [comment]
Fix will be deployed later today.

**Comment by boldninja** [comment]
Fixed, will be deployed later on today: https://github.com/ArkEcosystem/ark-explorer/commit/e71942349ad0d25a1bb301caed0c7e73dc05a99e

**Comment by zarkill** [comment]
Wow, you guys are fast. Appreciate your help!
