### ISSUE TITLE
Detail informations doesn't reload correctly

### ISSUE THREAD

**Issue by reConNico** [ArkEcosystem/ark-explorer#87]
When you're on a delegate detail page (e.g. https://explorer.ark.io/address/AWDdMBebDW56ffwisTNrHQ8yQZgiVbisDQ#/wallets/AeaqhUKfBtVqNhtMct3piBiWfdhbRwbg4W)

![delegate_detail](https://user-images.githubusercontent.com/15830979/35915922-026087da-0c09-11e8-8d7d-c0582737267a.png)

When you click on another address under tab transactions (e.g. AWDdM...bisDQ) then the delegate details doesn't disappear correctly.

![address_detail](https://user-images.githubusercontent.com/15830979/35915998-2eee5156-0c09-11e8-8e28-0cab1b307183.png)

You need to reload the page to get the correct details

![address_detail_correct](https://user-images.githubusercontent.com/15830979/35916005-37eb6d5c-0c09-11e8-8e09-70142c52f744.png)

**Comment by faustbrian** [comment]
Fixed, will be deployed later today. https://github.com/ArkEcosystem/ark-explorer/commit/6d4c3d66da2fbac2407155e0579d43c9a6949a62
