### ISSUE TITLE
Show More Button doesn't load more transactions

### ISSUE THREAD

**Issue by reConNico** [ArkEcosystem/ark-explorer#88]
When you go on the front page and click the "Show more" button in the tab "latest transactions" the button doesn't load more transactions. It just loads the first page of transactions `transactions/1` but not really more transactions.

Before click on show more button:

![ark_transactions](https://user-images.githubusercontent.com/15830979/35917060-f3e6911e-0c0c-11e8-9f72-be7b604cc408.png)

After click on button:

![ark_transactions_2](https://user-images.githubusercontent.com/15830979/35917063-f8227c98-0c0c-11e8-8d2a-15fdf50af464.png)

**Comment by faustbrian** [comment]
This is working as intended that it goes to a new page but we changed it so it goes to page 2, will be deployed later today.
