### ISSUE TITLE
Too much rounding. 

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-explorer#9]
In the new interface, it only shows 9.00 Ark 
In arkcoin.net, it shows the total value 9.00299711 Ark 
If the new interface shows the exact value, it would be great!

You should at least see the unrounded values somehow.

**Comment by faustbrian** [comment]
Agreed, especially when you offer a website for your voters and your own site and the explorer show different numbers.

**Comment by boldninja** [comment]
@luciorubeens I think this is a priority other things are not so pressing.
