### ISSUE TITLE
When "Show more" is clicked,  "Latest Transactions" and "Latest Blocks" submenus disappear

### ISSUE THREAD

**Issue by ayyyyyyyyyyyy** [ArkEcosystem/ark-explorer#90]
Then I must refresh the page... It does need "Latest Transactions" and "Latest Blocks" to be static on the top of the list, no?

**Comment by faustbrian** [comment]
It's the intended behaviour that you get to a new page when you click the show more button, that is why the "Menus" disappear because you are on a new page.
