### ISSUE TITLE
Votes, delegate and second passphrase registration has no placeholders

### ISSUE THREAD

**Issue by dafty** [ArkEcosystem/ark-explorer#94]
![image](https://user-images.githubusercontent.com/24987593/36027760-7b1e8e1a-0d94-11e8-8901-fad9c642babd.png)

**Comment by faustbrian** [comment]
Fixed, will be deployed later. https://github.com/ArkEcosystem/ark-explorer/commit/316e66804e33f2c75b66d08778c3e2cd7fce61d4
